### ISSUE TITLE
Export Results

### ISSUE THREAD

**Issue by peymvn** [MIT-LCP/querybuilder-issue#1]
Hi,
I used the QueryBuilder and found my desired data but when I tried exporting them as a CSV file with the "Export Results" button, the results were not the real data and they were just some web scripts in the CSV cells.
You may find a sample of that results in my [dropbox](https://www.dropbox.com/s/j2v3p1rh7vyxem1/Result.csv?dl=0).
Can anyone help me to export the results correctly?
Bests,
Peyman

**Comment by elfeto** [comment]
Hi, I apologize for the inconvenience, the software was updated and I forgot to also updated that page,  It should be working now.
