### ISSUE TITLE
I cannot have access to my mimic acount

### ISSUE THREAD

**Issue by rbighami** [MIT-LCP/querybuilder-issue#3]
Hi Admin,

For some reason I cannot have access to my mimic account and I get error when I put my username and password. 

Would you please help

Thank you

**Comment by elfeto** [comment]
Hi,

You log in with your email address, the same email and password as https://physionet.org/works/ 

Let me know if this helps, or if the problem persist.
Thanks!

**Comment by rbighami** [comment]
Hi,

I wonder if my account has been disabled. I used to use MIMIC II inquiry
builder for several years. I just noticed that the website has been changed
slightly and my username and password is not working.

My username and password is not working for https://physionet.org/works/
 either.

Thank you

**Comment by tompollard** [comment]
@rbighami Let's continue this discussion by email. We will be in touch.

**Comment by elfeto** [comment]
So, we moved to a new platform, and the accounts that were created for MIMIC II are no longer used. Those accounts were only for the other query builder. We merged Physionet Works authentication system with this one so there would be less accounts to keep track off. 

Your username would be your complete email address with the password you had in Physionet works. 

**Your account is not disabled.** 

If you still cannot login to the website, then you should reset your password at: https://physionet.org/pnw/login

Let me know if this works.
Thanks!

**Comment by rbighami** [comment]
Great, it worked.

Thank you very much for help.

Best regards
