### ISSUE TITLE
no repo for querybuilder-backend, querybuilder-frontend?

### ISSUE THREAD

**Issue by mg1075** [MIT-LCP/querybuilder-issue#4]
Are there supposed to be repositories for the querybuilder?
Both of the pages mentioned in .gitmodules return 404 error messages.
- https://github.com/MIT-LCP/querybuilder-backend
- https://github.com/MIT-LCP/querybuilder-frontend

**Comment by tompollard** [comment]
@mg1075 thanks for the post. The code is not publicly available right now - those are links to private repos. I have added a note to the readme to clarify this point: https://github.com/MIT-LCP/querybuilder-issue/blob/master/README.md

**Comment by elfeto** [comment]
Hi @mg1075  created another repo for querybuilder that is hosted on AWS EC2. That repo contains both the python backend and the frontend. it can be found here: https://github.com/MIT-LCP/QueryBuilder-AWS
