### ISSUE TITLE
Having trouble executing a query on BigQuery

### ISSUE THREAD

**Issue by kelly1854** [MIT-LCP/querybuilder-issue#7]
Hello!

I have been granted access: "Access to the GCP BigQuery was previously awarded to (me) for project: MIMIC-III Clinical Database v1.4".

I can see the mimiciii-clinical dataset in the Resources section on the left on BigQuery.

When I try to run this simple query (i.e., the first query listed in the tutorial):
SELECT *
FROM `physionet-data.mimiciii_clinical.patients`

I received the message: "Access Denied: Project physionet-data: User does not have bigquery.jobs.create permission in project physionet-data."

Any help or suggestions would be appreciated! Thanks!

**Comment by tompollard** [comment]
@kelly1854 please could you point to the tutorial that you are looking at? 

The solution may be to swap the project in the header menu from "physionet-data" to your personal project. If you click "physionet-data", you should see a dropdown offering alternatives. 

Please could you also check:
- that you have completed the steps at: https://github.com/MIT-LCP/mimic-code/issues/723 (it sounds like you have done, but it would be good to confirm).
- that you are logged into the same Google Account that is associated with your PhysioNet account.

**Comment by kelly1854** [comment]
Thanks @tompollard !

Here is the url for the tutorial: https://mimic.physionet.org/tutorials/intro-to-mimic-iii-bq/

Based on your suggestions, I created a new (personal) project and then added the physionet-data to it. I am now able to follow the tutorial to submit queries.

Thank you!

**Comment by tompollard** [comment]
@kelly1854 great, glad this helped! Please feel free to propose improvements to the tutorial (you can click "edit this page" at the bottom of the left menu).
